#!/bin/bash

# I AM PROTO
# SECURITY IS MY
# 				MOTTO
alias su="doas -s"
alias sudo="doas"

# NEOVIM
alias v="nvim"
alias sv="doas nvim"
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# LS AND SHIT
alias lf="ranger"
alias ls="ls --color"
alias la="ls -A"
alias ll="la -lh"
alias tra="tree -a"
tral () { tra $@ | less; }
alias grep="grep --color=always"
export LESS="Rij5"
catl () { cat $@ | less; }

# USEFUL COMMANDS
wifi () { doas ip link set dev wlan0 down; doas netctl start wlan0-$1; }  #restart wifi, connect to profile $1 for wireless
alias pp="ping -c 1 gnu.org"  #check connectivity
alias untar="tar -xvf"
alias dh="du -sh"
alias wm="doas wifi-menu"
alias sn="shutdown now"
alias sx="startx" #should honestly be in .profile
alias mkdir="mkdir -p"
alias clip="xclip -selection clipboard"
alias paste="clip -o"
alias bctl="bluetoothctl"
alias rml="rm *.fls *.fdb_latexmk *.log *.out *.synctex.gz *.aux"

# PACMAN-RELATED
alias pman="doas pacman"  #save keystrokes
alias orphant="yay -Qtdq | yay -Rns - --noconfirm" #yeet the child
alias update="/home/bit/src/wm/updater.sh"

# CONFIG EDIT + RELOAD
alias rbrc="source ~/.bashrc"
alias rzrc="source ~/.zshrc"
alias vvrc="v ~/.config/nvim/init.vim"
alias vlrc="v ~/.config/nvim/nvim.lua"
alias vbrc="v ~/.bashrc"
alias vzrc="v ~/.zshrc"
alias varc="v ~/.config/aliasrc"
alias cdwm="cd ~/src/wm"
alias cdpr="cd ~/src/proj"

# OTHER DEV ALIASES
alias aa="./a.out"
alias mci="doas make clean install"

# I USE ARCH BTW
alias btw="neofetch"
alias gtw="gnomefetch"

# TYPOS + CLEARING
alias claer="clear"
alias celar="clear"
alias cl="clear"
alias cls="cl;ls"
alias cla="cl;la"
alias cll="cl;ll"
alias cd..="cd .."

# V E R B O S E
alias cp="cp -v"
alias mv="mv -v"
alias rm="rm -v"
